# .github/workflows/app.yaml
name: PyTest
on: [push,pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          python3 -m pip install --upgrade pytest
          pip3 install pytest-cov

      - name: Run test suite
        run: |
          pytest ./offlinemot/tests --exitfirst --verbose --failed-first \
          --cov=./  --cov-report=xml

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos